version: 0.0
os: linux
files:
  - source: .
    destination: /home/rugia/git/blog/
hooks:
  AfterInstall:
   - location: echo "hi"
     timeout: 300
     runas: root
  ApplicationStart:
   - location: echo "hi"
     timeout: 300
     runas: root
